### ISSUE TITLE
Add support for Windows 10 dark mode

### ISSUE THREAD

**Issue by reupen** [reupen/columns_ui#417]
General tracking issue for tasks related to supporting the Windows 10 and 11 dark mode.

# Tasks

- [x] Make main window title bar and background dark
- [x] Make rebar dark
- [x] Make playlist view, playlist switcher, filters and item properties dark
- [x] Make DSP preset, output device, output format, playback order and ReplayGain mode toolbars dark
- [x] Make filter search dark
- [x] Make volume toolbar dark
- [x] Make track bars dark
- [x] Make status pane dark
- [x] Make status bar dark
- [x] Make status bar pop-up volume control dark
- [x] Make horizontal and vertical splitters dark
- [x] Make playlist tabs dark
- [x] Make tab stack dark
- [x] Make default button images dark
- [x] Make tooltips dark
- [x] Update light mode default button images
- [x] Optimise splitter background rendering
- [x] Reduce tab control flicker when resizing, and correct child background colour
- [x] Tweak playlist view drag and drop insertion line
- [x] Add missing rebar toolbar borders
- [x] Make filter search button images dark
- [x] Integrate spectrum analyser with colours and fonts settings
- [x] Add dark version of default artwork placeholder image (?)
- [ ] Tweak volume toolbar styling
- [x] Update themed colour patches on colours tab in preferences
- [x] Review handling of custom colours and mode switches
- [x] Review UI and colours for consistency
- [x] Review Windows 11 colours
- [x] Review Windows 11 dark menus
- [x] Review status bar playlist lock icon
- [x] Determine minimum supported Windows 10 version
- [x] [Test preview versions of Windows 11](https://docs.microsoft.com/en-gb/windows-insider/flight-hub/)
- [x] Add OS version checks before calling private Windows APIs
- [x] Add option in preferences
- [x] Add 'Use system setting' option
- [x] Make API and SDK changes
- [x] Integrate with API changes
- [x] Add dark mode settings to FCL files
- [x] Add dark mode toggle to quick set-up dialogue
- [x] Make album list panel dark
- [x] Make console panel dark
- [x] SDK: Improve dark mode docs
- [x] SDK: Improve uie::container_window

**Comment by razielanarki** [comment]
i would like to - if i may -  inject another lump of source code as reference here

this is an unfinished, but well researched attempt at the same thing 
(seeing as you're seriously started working on it, hopefully saving you some time,  )

tools used: IDA free disassembly, msstyleEditor, and some others

[Modern C++ loadlib wrapper + theme hackery GIST](https://gist.github.com/razielanarki/6d707ffdcf49709904feaec8210cb1cf)

may need some more explaining, but i was going to use the immersive colors (IMCLR_ constants) and window::HTMEME class->string extraction + prefixing (Darkmode:: + Darmode_Explorer:: ) + WM_THEMECHANGED stuff, to hack it better than the nodepad++ guys did :D )

(it seems that there's a Darkmode::Menu (!!), and such already in 19041, etc)

**Comment by reupen** [comment]
Thanks, that is useful and also a fair bit of reverse engineering 😄 

I did come across the immersive (UWP?) colours – but they didn't seem overly useful for Columns UI so I haven't used them.

My assumption is that Microsoft has given up on Win32 dark mode now (rewriting programs like Task Manager rather than adding a dark mode to the existing versions would seem to just be a further indication of that).

**Comment by marc2k3** [comment]
Maybe I'm jumping in too soon before it's ready but **on_bool_changed** is always triggered with the mask set to `bool_flag_dark_mode_enabled`, when switching between light/dark modes.

```cpp
void on_bool_changed(size_t mask) const override
{
	FB2K_console_formatter() << "on_bool_changed " << mask; // always 2
}
```

Tested with latest build of CUI available via actions artifacts, SDK is from master.

**Comment by reupen** [comment]
That's correct, it's indicating which flags have changed, rather than what the new values of all flags are:

https://columns-ui-sdk.readthedocs.io/en/latest/appearance/colours.html#_CPPv4NK3cui7colours6client15on_bool_changedE6t_size

The new value has to be queried using either `cui::colours::is_dark_mode_active()` or ``cui::colours::helper::is_dark_mode_active()`.

(The API could be better I'm sure, but it is what it is now. I can change the name of that parameter to something like `changed_flags_mask` though.)

**Comment by marc2k3** [comment]
I see. Thanks for the clarification.

**Comment by marc2k3** [comment]
I have my first proper bug to report. Toggling dark mode with toolbars hidden causes CUI to crash. Easy enough to reproduce so I'm won't bother with the txt/dmp.

**Comment by reupen** [comment]
Thanks for that, it should be resolved by #470.

**Comment by marc2k3** [comment]
Yup, it's fine now. Thanks.

**Comment by reupen** [comment]
The following linked screenshot appears to be confirmation that [the Windows 11 dark menu bug](https://github.com/reupen/columns_ui/pull/432#issuecomment-1061446048) is a generic bug:

https://github.com/microsoft/WindowsAppSDK/issues/41#issuecomment-1080342336

**Comment by reupen** [comment]
The scope of this issue is done now. New issues or discussions can be created for any follow-ups.
